### Mapping tests

### Get All Albums
GET http://localhost:8080/albums

### Get Single Album
GET http://localhost:8080/albums/6

### Get All Songs
GET http://localhost:8080/songs

### Get Single Song
GET http://localhost:8080/songs/8

### Create New album
POST http://localhost:8080/albums/addAlbum
Content-Type: application/json

{
  "title": "new album",
  "image": "img3",
  "recordLabel": "ls",
  "songs": [],
  "comments": [
    "it's the best"
  ],
  "ratings": 4
}

### Add Song to Album
PATCH http://localhost:8080/albums/6/addSong
Content-Type: application/json

{
  "songTitle": "ifyouseekamy",
  "duration": "5:66"
}

### Add comment to album
Patch http://localhost:8080/albums/3/addComment

actually awesome

### add comment to song
PATCH http://localhost:8080/songs/22/addSongComment

beatch


### add Rating to album
PATCH http://localhost:8080/albums/6/addRating
Content-Type: application/json

100

### add rating to song
PATCH http://localhost:8080/songs/22/addRating
Content-Type: application/json

10

### Delete an album 
DELETE http://localhost:8080/albums/6

### Delete a song 
DELETE  http://localhost:8080/songs/22

### Change Album Title
PATCH  http://localhost:8080/albums/3

ryans loves songs vol. 9

### Change Song Title
PATCH http://localhost:8080/songs/24

its brittney