### Get Albums

GET http://localhost:8080/albums

### Get Single Album
GET http://localhost:8080/albums/3

### Get Songs
GET http://localhost:8080/songs

### Add Song to Album
POST http://localhost:8080/albums/3/addSong
Content-Type: application/json

{
    "songTitle": "Random title",
      "duration": "5:37",
      "ratings": 3,
      "comments": [
        "unique"
      ]
}
### Create a new album
POST http://localhost:8080/albums/addAlbum
Content-Type: application/json

{
  "title": "go away",
  "image": "img3",
  "recordLabel": "ls",
  "songs": [],
  "comments": [
    "it's the best"
  ],
  "ratings": 4
}

### Delete an album 
DELETE http://localhost:8080/albums/26

### Delete a song 
DELETE  http://localhost:8080/songs/8
