### Mapping tests

### Get All Albums
GET http://localhost:8080/albums

### Get Single Album
GET http://localhost:8080/albums/3

### Get All Songs
GET http://localhost:8080/songs

### Get Single Song
GET http://localhost:8080/songs/8


### Add Song to Album
POST http://localhost:8080/albums/3/addSong
Content-Type: application/json

{
    "songTitle": "Random title",
      "duration": "5:37",
      "ratings": 3,
      "comments": [
        "unique"
      ]
}
### Create New album
POST http://localhost:8080/albums/addAlbum
Content-Type: application/json

{
  "title": "go away",
  "image": "img3",
  "recordLabel": "ls",
  "songs": [],
  "comments": [
    "it's the best"
  ],
  "ratings": 4
}

### Delete an album 
DELETE http://localhost:8080/albums/19

### Delete a song 
DELETE  http://localhost:8080/songs/18

### Change Album Title
PATCH  http://localhost:8080/albums/3

ryans mixtape vol. 7

### Change Song Title
PATCH http://localhost:8080/songs/11/

i miss you so much